### PR TITLE
Small PHP 7 fixes

### PR DESCRIPTION
**Pull request by bbrala**
I'm updating some old sites to PHP 7 and came across this package. I've fixed the issues it has in PHP 7 so it works. :)

### CODE REVIEW

**Comment by balupton** [comment]
Cool! Before I look into it, seems tabs have been replaced with spaces, can you ammend it having tabs again? As otherwise every line changes. Cheers

**Comment by bbrala** [comment]
Ah yeah, will do that later today.

**Comment by bbrala** [comment]
@balupton think this should do. :)

**Comment by RaymondBenc** [comment]
I've applied this PR in our project and works great now on PHP 7.

**Comment by bbrala** [comment]
Glad it works for you, i had about 5 old projects which used this :) Hopefully @balupton will merge is sometime soon.

**Pull request merged**
